# Generated by Django 3.0.14 on 2025-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
